-- truncate table okr_acme.alignment cascade;
-- truncate table okr_acme.action cascade;
-- truncate table okr_acme.check_in cascade;
-- truncate table okr_acme.key_result cascade;
-- truncate table okr_acme.completed cascade;
-- truncate table okr_acme.objective cascade;
-- truncate table okr_acme.person cascade;
-- truncate table okr_acme.quarter cascade;
-- truncate table okr_acme.team cascade;
-- truncate table okr_acme.person_team cascade;
-- truncate table okr_acme.unit cascade;

truncate table alignment cascade;
truncate table action cascade;
truncate table check_in cascade;
truncate table key_result cascade;
truncate table completed cascade;
truncate table objective cascade;
truncate table person cascade;
truncate table quarter cascade;
truncate table team cascade;
truncate table person_team cascade;
truncate table unit cascade;