include:
  - ../docker-compose.yml
services:
  spring:
    tty: true
    container_name: spring
    build:
      context: .
      dockerfile: local-prod.Dockerfile
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration,classpath:db/data-migration,classpath:db/callback
    volumes:
        - ../../../okr/backend/target:/app-root/backend
    network_mode: "host"

  maven:
    tty: true
    container_name: maven
    image: maven:3.9.9-amazoncorretto-21
    command: sh -c "mvn -B clean package -P build-for-docker,debug && mvn fizzed-watcher:run"
    working_dir: /app-root/
    volumes:
      - ../../../okr:/app-root/
      - ~/.m2/repository:/root/.m2/repository

  angular:
    container_name: angular
    image: node:20
    tty: true
    volumes:
      - ../../../okr:/opt
    command: [ "/bin/bash", "-c", "cd /opt/frontend && mkdir -p dist && npm ci && npm run watch:prod" ]
