include:
  - ../docker-compose.yml
services:
  spring:
    container_name: spring
    build:
      context: .
      dockerfile: local-prod.Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: staging
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: debug
    volumes:
        - ../../../okr/backend/target:/app-root/backend

  maven:
    container_name: maven
    image: maven:3.9.9-amazoncorretto-21
    command: sh -c "mvn fizzed-watcher:run"
    working_dir: /app-root/
    volumes:
      - ../../../okr:/app-root/
      - ~/.m2/repository:/root/.m2/repository

  angular:
    container_name: angular
    image: node:22
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../../../okr:/opt
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: [ "/bin/bash", "-c", "cd /opt/frontend && npm ci && npm run watch:prod" ]
