services:
  spring:
    container_name: spring
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: staging
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: debug
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://localhost:8544/realms/pitc
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: http://keycloak:8080/realms/pitc/protocol/openid-connect/certs
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: https://sso.puzzle.ch/auth/realms/pitc
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: https://sso.puzzle.ch/auth/realms/pitc/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT-ID: pitc_okr_staging
      SPRING_DATASOURCE_URL: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: sa
      SPRING_FLYWAY_LOCATIONS: classpath:db/h2-db/database-h2-schema,classpath:db/h2-db/data-test-h2
    networks:
      - okr-network
    depends_on:
      build-maven:
        condition: service_completed_successfully

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.5
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
    volumes:
      - ../config/realm-export.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm
    ports:
      - 8544:8080
    networks:
      - okr-network

  build-maven:
    container_name: maven
    image: maven:3.8.3-openjdk-17
    user: root
    volumes:
      - ../../../okr:/opt
    command: [ "/bin/bash", "-c", "cd /opt && mvn -B clean package --file pom.xml -P build-for-docker" ]
    depends_on:
      build-angular:
        condition: service_completed_successfully

  build-angular:
    container_name: angular
    image: node:20
    user: root
    volumes:
      - ../../../okr/frontend:/opt
    command: [ "/bin/bash", "-c", "cd /opt && npm run build" ]

networks:
  okr-network:
