version: '3.5'

services:
  keycloakIdp:
    image: quay.io/keycloak/keycloak:23.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
    volumes:
      - ./config/realm-export.json:/opt/keycloak/data/import/realm.json
      - ./config/keycloak-config.conf:/opt/keycloak/conf/keycloak.conf
      - ./keycloak_data_idp:/opt/keycloak/data/
    command:
      - start-dev
      - --import-realm
    network_mode: host
    restart: always

  keycloakBroker:
    image: quay.io/keycloak/keycloak:23.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
    volumes:
      - ./config/realm-export-broker.json:/opt/keycloak/data/import/realm.json
      - ./config/keycloak-broker-config.conf:/opt/keycloak/conf/keycloak.conf
      - ./keycloak_data_broker:/opt/keycloak/data/
    command:
      - start-dev
      - --import-realm
    network_mode: host
    restart: always
