ALTER TABLE MEASURE
    RENAME VALUE TO VALUE_METRIC;
ALTER TABLE MEASURE
    ALTER COLUMN VALUE_METRIC DROP NOT NULL,
ALTER
COLUMN MEASURE_DATE DROP
NOT NULL,
    ALTER
COLUMN CHANGE_INFO DROP
NOT NULL,
    ALTER
COLUMN CHANGE_INFO TYPE VARCHAR(4096),
    ADD COLUMN CONFIDENCE    INTEGER,
    ADD COLUMN CHECK_IN_TYPE VARCHAR(255),
    ADD COLUMN ZONE TEXT;
ALTER TABLE MEASURE
    RENAME MEASURE_DATE TO MODIFIED_ON;

UPDATE MEASURE
SET CONFIDENCE = 5;
UPDATE MEASURE
SET CHECK_IN_TYPE = 'metric';

ALTER TABLE "public"."measure"
    RENAME TO "check_in";
ALTER TABLE "public"."sequence_measure"
    RENAME TO "sequence_check_in";

DROP VIEW IF EXISTS OVERVIEW;
CREATE VIEW OVERVIEW AS
SELECT T.ID                AS "TEAM_ID",
       T.NAME              AS "TEAM_NAME",
       COALESCE(O.ID, -1)  AS "OBJECTIVE_ID",
       O.TITLE             AS "OBJECTIVE_TITLE",
       O.STATE             AS "OBJECTIVE_STATE",
       Q.ID                AS "QUARTER_ID",
       Q.LABEL             AS "QUARTER_LABEL",
       COALESCE(KR.ID, -1) AS "KEY_RESULT_ID",
       KR.TITLE            AS "KEY_RESULT_TITLE",
       KR.UNIT,
       KR.BASELINE,
       KR.STRETCH_GOAL,
       KR.COMMIT_ZONE,
       KR.TARGET_ZONE,
       KR.STRETCH_ZONE,
       COALESCE(C.ID, -1)  AS "CHECK_IN_ID",
       C.VALUE_METRIC      AS "CHECK_IN_VALUE",
       C.ZONE              AS "CHECK_IN_ZONE",
       C.CONFIDENCE,
       C.CREATED_ON
FROM TEAM T
         LEFT JOIN OBJECTIVE O ON T.ID = O.TEAM_ID
         LEFT JOIN QUARTER Q ON O.QUARTER_ID = Q.ID
         LEFT JOIN KEY_RESULT KR ON O.ID = KR.OBJECTIVE_ID
         LEFT JOIN CHECK_IN C ON KR.ID = C.KEY_RESULT_ID AND C.MODIFIED_ON = (SELECT MAX(CC.MODIFIED_ON)
                                                                              FROM CHECK_IN CC
                                                                              WHERE CC.KEY_RESULT_ID = C.KEY_RESULT_ID);