#!/bin/sh
GIT_BASE_PATH=$(git rev-parse --show-toplevel)
BACKEND_PATH="$GIT_BASE_PATH"/backend
FRONTEND_PATH="$GIT_BASE_PATH"/frontend
FORMATTED_FILE_EXTENSIONS="java|ts|html|css|scss|xml|json|yml|yaml|mjs"

gitBasePath=$(git rev-parse --show-toplevel)
addedFiles=$(git diff --cached --name-only --diff-filter=d --line-prefix="${gitBasePath}"/)

has_changed() {
    files=$1
    echo "$files" | grep -q .
}


frontend_files=$(get_changed_files "$FRONTEND_PATH")
backend_files=$(get_changed_files "$BACKEND_PATH")
echo "*****Running prettier******"
cd "$gitBasePath"/frontend || exit
npm run esl-format-specific "$addedFiles"
npm run prettier-format "$addedFiles"
echo "*****Finish running prettier******"

echo "---------------------------------------------------------"

echo "*****Running eslint******"
cd "$FRONTEND_PATH" || exit
has_changed "$frontend_files" && npm run lint:format:specific $frontend_files || echo "No files found to format"
echo "*****Finish running eslint******"

echo "---------------------------------------------------------"

echo "*****Running maven formatter******"
cd "$gitBasePath" || exit
mvn -f backend/pom.xml spotless:apply -DspotlessFiles="$addedFiles"
echo "*****Finish running maven formatter******"

echo "---------------------------------------------------------"

echo "*****Adding changes to git******"
cd "$gitBasePath" || exit
# shellcheck disable=SC2086
git add $addedFiles
echo "*****Formatted files added again******"

status=$?
exit $status

