#!/bin/sh
GIT_BASE_PATH=$(git rev-parse --show-toplevel)
BACKEND_PATH="$GIT_BASE_PATH"/backend
FRONTEND_PATH="$GIT_BASE_PATH"/frontend
FORMATTED_FILE_EXTENSIONS="java|ts|html|xml|json|yml|yaml|mjs"

get_changed_files() {
    GIT_BASE_PATH=$(git rev-parse --show-toplevel)
    path=$1
    git diff --cached  --name-only --diff-filter=d --line-prefix="$GIT_BASE_PATH"/ "$path" | tr '\n' ' ' | xargs | grep "\.($FORMATTED_FILE_EXTENSIONS)$"
}

has_changed() {
    files=$1
    echo "$files" | grep -q .
}


frontend_files=$(get_changed_files "$FRONTEND_PATH")
backend_files=$(get_changed_files "$BACKEND_PATH")

echo "*****Running prettier******"
cd "$FRONTEND_PATH" || exit
has_changed "$frontend_files" && npm run prettier:lint:format:specific "$frontend_files" || echo "No files found to format"
echo "*****Finish running eslint******"

echo "---------------------------------------------------------"

echo "*****Running eslint******"
cd "$FRONTEND_PATH" || exit
has_changed "$frontend_files" && npm run lint:format:specific "$frontend_files" || echo "No files found to format"
echo "*****Finish running eslint******"

echo "---------------------------------------------------------"

echo "*****Running maven formatter******"
cd "$BACKEND_PATH" || exit
# shellcheck disable=SC2091
has_changed "$backend_files" && mvn -f pom.xml spotless:apply -DspotlessFiles="$backend_files" || echo "No files found to format"
echo "*****Finish running maven formatter******"

echo "---------------------------------------------------------"

echo "*****Adding changes to git******"
cd "$GIT_BASE_PATH" || exit

has_changed "$frontend_files" && git add "$frontend_files" -v || echo "No frontend files changed, nothing to add"
has_changed "$backend_files" && git add "$backend_files" -v || echo "No backend files files changed, nothing to add"
echo "*****Formatted files added again******"

status=$?
exit $status

