name: Build with provenance
on: [push]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
    - uses: slsa-framework/slsa-github-generator/.github/workflows/builder_maven_slsa3.yml@v1.9.0
      env:
        PACKAGE_DIR: ./backend