name: 'Show Variables'

on:
  workflow_dispatch:
    inputs:
      deployment_type:
        type: choice
        description: Select type of deployment
        options:
          - Major
          - Minor
          - Patch
          - Release from Commit
      commit_hash:
        description: 'The hash of thee commit that should be deployed, defaults to the latest commit on main'
        required: false
        type: string

jobs:
  set-commit:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      id-token: write
      contents: write
      attestations: write
    outputs:
      SHORT_HASH: "${{ env.SEMVER_VERSION }}-${{ env.SHORT_COMMIT_HASH }}"
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Try to show GitHub Variables
        run: |
          echo "deployment_type is ${{ github.event.inputs.deployment_type }}" / ${{ inputs.deployment_type }}
          echo "commit_hash is ${{ github.event.inputs.commit_hash }}" / ${{ inputs.commit_hash }}
          
      - name: Get current directory
        run: |
          echo "Current directory is $(pwd)"

      - name: Stores the commit hash as environment variable
        run: |
          commit_hash=$(./scripts/get-commit.sh ${{ env.BRANCH_NAME }} ${{ github.event.inputs.commit_hash }})
          echo "Commit is set to \"$commit_hash\""
          echo "SHORT_COMMIT_HASH=$(git rev-parse --short $commit_hash)" >> $GITHUB_ENV

      - name: Accessing the environment variable
        run: |
          echo "${{ env.SHORT_COMMIT_HASH }}"

#  update-semver:
#    needs: set-commit
#    runs-on: ubuntu-latest
#    steps:


