name: 'Show Variables'

on:
  workflow_dispatch:
    inputs:
      deployment_type:
        type: choice
        description: Select type of deployment
        options:
          - Major
          - Minor
          - Patch
      commit_hash:
        description: 'The hash of thee commit that should be deployed, defaults to the latest commit on main'
        required: false
        type: string

jobs:
  display-variables:
    name: Show GitHub Variables
    runs-on: ubuntu-24.04
    steps:
    - name: Try to show GitHub Variables
      run: |
        echo "repository variable : ${{ vars.REPOSITORY_VAR }}"
        echo "organization variable : ${{ vars.ORGANIZATION_VAR }}"
        echo "overridden variable : ${{ vars.OVERRIDE_VAR }}"
        echo "variable from shell environment : $env_var"
        echo "IMAGE_TAG : $vars.ENV_CONTEXT_VAR"
        echo "IMAGE_TAG : $IMAGE_TAG"
        echo "QUAY_URL : $QUAY_URL"
        echo "deployment_type is ${{ github.event.inputs.deployment_type }}" / ${{ inputs.deployment_type }}
        echo "commit_hash is ${{ github.event.inputs.commit_hash }}" / ${{ inputs.commit_hash }}

    
