name: 'Show Variables'

on:
  workflow_dispatch:
    inputs:
      deployment_type:
        type: choice
        description: Select type of deployment
        options:
          - Major
          - Minor
          - Patch
      commit_hash:
        description: 'The hash of thee commit that should be deployed, defaults to the latest commit on main'
        required: false
        type: string

jobs:
  create-image_tag:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      id-token: write
      contents: write
      attestations: write
    #    outputs:
    #      imageVersion: "${{ env.SEMVER_VERSION }}-${{ env.SHORT_COMMIT_HASH }}"
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Try to show GitHub Variables
        run: |
          echo "deployment_type is ${{ github.event.inputs.deployment_type }}" / ${{ inputs.deployment_type }}
          echo "commit_hash is ${{ github.event.inputs.commit_hash }}" / ${{ inputs.commit_hash }}

      - name: Stores the commit hash as environment variable
        run: |
          if [ -z "$commit_hash" ]; then
            echo "Commit is not set, default to last commit of branch \"${{ env.BRANCH_NAME }}\""
            commit_hash="$(git rev-parse @)"
          fi
          
          if  git rev-parse --quiet --verify $commit_hash; then
            commit_hash=$(git rev-parse --verify $commit_hash)
            echo "Commit is valid"
          else
            echo "Commit \"$commit_hash\" is not valid"
            exit 1
          fi
          
          if [ "$(git merge-base $commit_hash ${{ env.BRANCH_NAME }})" != "$commit_hash" ]; then
            echo "Commit is not from branch \"${{ env.BRANCH_NAME }}\""
            exit 1
          fi
          
          
          echo "Commit is set to \"$commit_hash\""
          echo "SHORT_COMMIT_HASH=$(git rev-parse --short $commit_hash)" >> $GITHUB_ENV
      - name: Accessing the environment variable
        run: |
          echo "${{ env.SHORT_COMMIT_HASH }}"
          

