name: 'Show Variables'

on:
  push:

jobs:
  sonarqube:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: ${{ vars.JAVA_VERSION }}
            distribution: 'temurin'
        - name: Build and analyze
          run: mvn clean verify sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    
